version: "3.0"
services:
  backend:
    build: "./backend"
    ports:
      - "3000:3000"
    links:
      - mariadb
      - mongodb
    networks:
      - project
  
  vuefront:
    build: "./vuefront"
    stdin_open: true
    tty : true
    ports:
      - "80:8080"
    links:
      - backend
    networks:
      - project

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
      - project
  
  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=user
    ports:
      - "3306:3306"
    networks:
      - project

networks:
  project:
    driver: bridge