version: "3.0"
services:
  backend:
    build: "./backend"
    ports:
      - "3000:3000"
    networks:
      - project
  
  vuefront:
    build: "./vuefront"
    stdin_open: true
    tty : true
    ports:
      - "80:8080"
    networks:
      - project

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
      - project
  
networks:
  project: